default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: storerails_dev

test:
  <<: *default
  database: storerails_test

production:
  <<: *default
  database: storerails_prod